name: clang-format Check

on:
  pull_request:
    types: [opened, review_requested, synchronize]
    # Only trigger if C source files have been changed.
    paths:
      - "**.c"
      - "**.h"
  push:
    branches:
      - main

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Filter only files changed by the PR.
      - name: Filter changed files
        id: filter
        uses: dorny/paths-filter@v3
        with:
          list-files: shell
          filters: |
            c:
              - '**.c'
            h:
              - '**.h'
      # Check code.
      - name: Run clang-format style check for C.
        if: steps.filter.outputs.c == 'true' || steps.filter.outputs.h == 'true'
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: "18"
          check-path: "kernel"
          fallback-style: llvm
          include-regex: ${{ steps.filter.outputs.c_files }} ${{ steps.filter.outputs.h_files }}
